import type { ExcelCNAEditorProps } from "./schema";

export const excelCnaEditorInput: ExcelCNAEditorProps = {
  adId: "manual-test-A005",
  brandName: "ExcelCNA",
  voiceoverUrl:
    "https://storage.googleapis.com/excelcna-images/social-videos/start-hca-training-washington-simple-first-step/voiceover.mp3",
  primaryColor: "#0E7490",
  secondaryColor: "#F59E0B",
  textColor: "#F8FAFC",
  accentColor: "#FDE68A",
  surfaceColor: "#08101F",
  scenes: [
    {
      id: "scene-01",
      role: "hook",
      startMs: 0,
      endMs: 4534,
      mediaUrl:
        "https://images.pexels.com/photos/9159667/pexels-photo-9159667.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      mediaType: "image",
      headline: "HCA training in Washington?",
      transition: "slide",
      overlays: [
        {
          id: "overlay-1-1",
          type: "underline_sweep",
          startMs: 0,
          endMs: 800,
          color: "#F59E0B",
          target: "caption",
        },
      ],
    },
    {
      id: "scene-02",
      role: "pain",
      startMs: 4534,
      endMs: 9975,
      mediaUrl:
        "https://images.pexels.com/photos/6963063/pexels-photo-6963063.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      mediaType: "image",
      headline: "The path feels confusing",
      transition: "wipe",
      overlays: [
        {
          id: "overlay-2-1",
          type: "highlight_box",
          startMs: 4534,
          endMs: 5334,
          color: "#0E7490",
          target: "frame",
        },
      ],
    },
    {
      id: "scene-03",
      role: "solution",
      startMs: 9975,
      endMs: 16323,
      mediaUrl:
        "https://images.pexels.com/photos/7013241/pexels-photo-7013241.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      mediaType: "image",
      headline: "Start with a clear setup",
      transition: "fade",
      overlays: [
        {
          id: "overlay-3-1",
          type: "ring_pulse",
          startMs: 9975,
          endMs: 10775,
          color: "#FDE68A",
          target: "frame",
        },
      ],
    },
    {
      id: "scene-04",
      role: "proof",
      startMs: 16323,
      endMs: 22218,
      mediaUrl:
        "https://images.pexels.com/photos/6994291/pexels-photo-6994291.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      mediaType: "image",
      headline: "Starting at $95 down",
      transition: "wipe",
      overlays: [
        {
          id: "overlay-4-1",
          type: "glow_blob",
          startMs: 16323,
          endMs: 17123,
          color: "#F59E0B",
          target: "caption",
        },
      ],
    },
    {
      id: "scene-05",
      role: "offer",
      startMs: 22218,
      endMs: 28566,
      mediaUrl:
        "https://images.pexels.com/photos/5756750/pexels-photo-5756750.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      mediaType: "image",
      headline: "DSHS-approved HCA training",
      transition: "fade",
      overlays: [
        {
          id: "overlay-5-1",
          type: "underline_sweep",
          startMs: 22218,
          endMs: 23018,
          color: "#0E7490",
          target: "frame",
        },
      ],
    },
    {
      id: "scene-06",
      role: "cta",
      startMs: 28566,
      endMs: 35367,
      mediaUrl:
        "https://images.pexels.com/photos/8408538/pexels-photo-8408538.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      mediaType: "image",
      headline: "Tap to see HCA details",
      transition: "slide",
      overlays: [
        {
          id: "overlay-6-1",
          type: "scribble_draw",
          startMs: 28566,
          endMs: 29366,
          color: "#FDE68A",
          target: "frame",
        },
      ],
    },
  ],
  captions: [
    {
      id: "caption-1",
      text: "Thinking about HCA training in Washington?",
      startMs: 0,
      endMs: 2717,
      type: "phrase",
      effect: "auto",
    },
    {
      id: "caption-2",
      text: "Here’s the easiest first step.",
      startMs: 2717,
      endMs: 4610,
      type: "phrase",
      effect: "auto",
    },
    {
      id: "caption-3",
      text: "If you’re not sure where to begin, it’s usually because the path feels confusing—forms, requirements, and timing.",
      startMs: 4610,
      endMs: 11277,
      type: "phrase",
      effect: "auto",
    },
    {
      id: "caption-4",
      text: "So start with the training setup that’s built for new students: sign up, complete the online portion, and get your plan for the rest.",
      startMs: 11277,
      endMs: 18545,
      type: "phrase",
      effect: "auto",
    },
    {
      id: "caption-5",
      text: "You can begin with a small down payment—starting at $95—then continue from there.",
      startMs: 18545,
      endMs: 23762,
      type: "phrase",
      effect: "auto",
    },
    {
      id: "caption-6",
      text: "This program is designed to prepare you for HCA work, with DSHS-approved HCA training.",
      startMs: 23762,
      endMs: 29705,
      type: "phrase",
      effect: "auto",
    },
    {
      id: "caption-7",
      text: "If you’re ready to stop guessing and follow a clear next step, tap the link and see the HCA details for Washington.",
      startMs: 29705,
      endMs: 35367,
      type: "phrase",
      effect: "auto",
    },
  ],
};
